name: Test and Upload artifact

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: upp_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        java: [ 17 ]
    name: Run unit tests on Java ${{ matrix.java }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 1
          done

      - name: Run tests
        run: mvn -f pom.xml clean test

  release:
    runs-on: ubuntu-latest
    needs: test
    name: Build, package and upload .jar artifact
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build and package project
        run: mvn -f pom.xml clean package

      - name: Show contents of the current working directory
        run: ls -la

      - name: Show contents of a target directory
        run: ls -la target

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./target/*.jar
